def register(F,C,B,I):
 B('rdOn','rd_on','Resonant Delay Enabled','Space',False,'Stereo delay with a normalized modal processor inside the feedback path.')
 F('rdTime','rd_time','Resonant Delay Time','Space',1,4000,375,'ms','Ms','Delay time; changes glide smoothly.',centre=400)
 B('rdSync','rd_sync','Resonant Delay Sync','Space',False,'Use the host tempo and selected note division.')
 C('rdDiv','rd_div','Resonant Delay Division','Space','SyncDivs',6,'Tempo-synchronized note division.')
 F('rdFeedback','rd_feedback','Resonant Delay Feedback','Space',0,.98,.5,'%','Percent','Normalized feedback; new excitation follows loop loss.')
 C('rdType','rd_type','Delay Resonator Type','Space','DelayResTypes',0,'Six-mode harmonic, bar, membrane or vowel-like feedback colour. Changes glide between frequencies.')
 F('rdTuning','rd_tuning','Delay Resonator Tuning','Space',20,6000,220,'Hz','Hz','Base frequency of the first feedback mode, referenced to MIDI note 57 when tracking.',centre=440)
 F('rdTrack','rd_track','Delay Pitch Tracking','Space',0,1,0,'%','Percent','Follow the last MIDI note relative to A3. Pitch bend and per-voice glide do not change this shared effect.')
 F('rdDamping','rd_damping','Delay Resonator Damping','Space',0,1,.4,'%','Percent','Shorten modal ringing and reduce upper-mode weights.')
 F('rdDispersion','rd_dispersion','Delay Resonator Dispersion','Space',0,1,0,'%','Percent','Stretch upper modal ratios for inharmonic repeat colour.')
 F('rdAmount','rd_amount','Delay Resonator Amount','Space',0,1,.7,'%','Percent','Blend neutral and modal-processed feedback. First repeat is unchanged.')
 F('rdSaturation','rd_saturation','Resonant Delay Saturation','Space',0,1,.2,'%','Percent','Gain-compensated soft saturation inside the feedback path.')
 F('rdOffset','rd_offset','Resonant Delay Stereo Offset','Space',-50,50,7,'ms','Ms','Difference between left and right delay times.')
 F('rdMix','rd_mix','Resonant Delay Mix','Space',0,1,.3,'%','Percent','Linear dry/wet blend; bypass fades and clears the delay.')
