#pragma once
// GENERATED by scripts/gen_params.py - do not edit by hand. Stable parameter IDs: never rename.
#include <juce_core/juce_core.h>

namespace aeriform
{
/** Every parameter, in layout order. Index == position in parameterInfos(). */
enum class P : int
{
    excNoise,
    excNoiseColor,
    excPressure,
    excPluck,
    excPluckLength,
    excLowpass,
    excHighpass,
    excTurbulence,
    excVelocity,
    excExternalIn,
    excKeyTrack,
    excAttackClick,
    excReleaseNoise,
    excBreathRandom,
    excReed,
    envAttack,
    envDecay,
    envSustain,
    envRelease,
    envVelToPressure,
    artPressBright,
    artFlowPitch,
    artInstability,
    artVariation,
    artCoupling,
    resCoarse,
    resFine,
    resLength,
    resKeyTrack,
    resFeedback,
    resDamping,
    resBrightness,
    resDispersion,
    resShape,
    resReflection,
    resSaturation,
    resMode,
    resBodyFreq,
    resBodyRes,
    resBodyMix,
    resBodyTrack,
    lfo1Shape,
    lfo1Rate,
    lfo1Sync,
    lfo1Div,
    lfo1Mode,
    lfo1Fade,
    lfo1Phase,
    lfo2Shape,
    lfo2Rate,
    lfo2Sync,
    lfo2Div,
    lfo2Mode,
    lfo2Fade,
    lfo2Phase,
    lfo3Shape,
    lfo3Rate,
    lfo3Sync,
    lfo3Div,
    lfo3Mode,
    lfo3Fade,
    lfo3Phase,
    menvAttack,
    menvDecay,
    menvSustain,
    menvRelease,
    mod1Src,
    mod1Dst,
    mod1Depth,
    mod2Src,
    mod2Dst,
    mod2Depth,
    mod3Src,
    mod3Dst,
    mod3Depth,
    mod4Src,
    mod4Dst,
    mod4Depth,
    mod5Src,
    mod5Dst,
    mod5Depth,
    mod6Src,
    mod6Dst,
    mod6Depth,
    mod7Src,
    mod7Dst,
    mod7Depth,
    mod8Src,
    mod8Dst,
    mod8Depth,
    chorusMix,
    chorusRate,
    chorusDepth,
    chorusWidth,
    delayMix,
    delayTime,
    delaySync,
    delayDiv,
    delayFeedback,
    delayTone,
    delayPingPong,
    reverbMix,
    reverbSize,
    reverbDecay,
    reverbDamping,
    reverbPreDelay,
    reverbWidth,
    reverbModulation,
    voiceMode,
    voiceCount,
    glideTime,
    glideLegatoOnly,
    unisonVoices,
    unisonDetune,
    unisonSpread,
    bendRange,
    mpeEnabled,
    outGain,
    outHighpass,
    limiterOn,
    exaModel,
    exaLevel,
    exaCoarse,
    exaFine,
    exaKeytrack,
    exaRetrig,
    exaVariation,
    exaVel,
    exaPress,
    exaDrift,
    exaPhase,
    exaTone,
    exaWaveShape,
    exaWavePw,
    exaWaveSub,
    exaWavePd,
    exaCxComplexity,
    exaCxSymmetry,
    exaCxBend,
    exaCxInstab,
    exaCxSpread,
    exaCxWarp,
    exaCxFeedback,
    exaCxChaos,
    exaCxRatio,
    exaNzColor,
    exaNzDensity,
    exaNzGrain,
    exaNzBandwidth,
    exaNzCenter,
    exaNzCorrelation,
    exaNzSeed,
    exaNzWidth,
    exaNzBurst,
    exaNzBurstEnv,
    exaNzTurb,
    exaNzGust,
    exaPhStiffness,
    exaPhOpening,
    exaPhPosition,
    exaPhSpeed,
    exaPhTurb,
    exaPhHardness,
    exaPhBright,
    exaScLp,
    exaScHp,
    exaScFollow,
    exaScTransient,
    exaScFreeze,
    exbModel,
    exbLevel,
    exbCoarse,
    exbFine,
    exbKeytrack,
    exbRetrig,
    exbVariation,
    exbVel,
    exbPress,
    exbDrift,
    exbPhase,
    exbTone,
    exbWaveShape,
    exbWavePw,
    exbWaveSub,
    exbWavePd,
    exbCxComplexity,
    exbCxSymmetry,
    exbCxBend,
    exbCxInstab,
    exbCxSpread,
    exbCxWarp,
    exbCxFeedback,
    exbCxChaos,
    exbCxRatio,
    exbNzColor,
    exbNzDensity,
    exbNzGrain,
    exbNzBandwidth,
    exbNzCenter,
    exbNzCorrelation,
    exbNzSeed,
    exbNzWidth,
    exbNzBurst,
    exbNzBurstEnv,
    exbNzTurb,
    exbNzGust,
    exbPhStiffness,
    exbPhOpening,
    exbPhPosition,
    exbPhSpeed,
    exbPhTurb,
    exbPhHardness,
    exbPhBright,
    exbScLp,
    exbScHp,
    exbScFollow,
    exbScTransient,
    exbScFreeze,
    exbSync,
    mixMode,
    mixInteraction,
    mixBalance,
    mixDepth,
    mixB2A,
    mixA2B,
    mixDcBlock,
    mixNormalize,
    mixDrive,
    preType,
    preRes,
    preDrive,
    preBias,
    preSlew,
    preTransient,
    preEnv,
    preOrder,
    wfOn,
    wfFold,
    wfDrive,
    wfSymmetry,
    wfBias,
    wfStages,
    wfMode,
    wfShape,
    wfMix,
    wfComp,
    wfLp,
    dynAmount,
    resOn,
    resInput,
    resOutput,
    resPan,
    resWidth,
    resPickup,
    resInharm,
    resSize,
    rbOn,
    rbType,
    rbInput,
    rbOutput,
    rbCoarse,
    rbFine,
    rbRatio,
    rbKeytrack,
    rbFeedback,
    rbDamping,
    rbBrightness,
    rbDispersion,
    rbInharm,
    rbShape,
    rbReflect,
    rbSaturation,
    rbReed,
    rbSize,
    rbPickup,
    rbPan,
    rbWidth,
    rcOn,
    rcType,
    rcInput,
    rcOutput,
    rcCoarse,
    rcFine,
    rcRatio,
    rcKeytrack,
    rcFeedback,
    rcDamping,
    rcBrightness,
    rcDispersion,
    rcInharm,
    rcShape,
    rcReflect,
    rcSaturation,
    rcReed,
    rcSize,
    rcPickup,
    rcPan,
    rcWidth,
    netMode,
    netFeedback,
    netAB,
    netBA,
    netBC,
    netCB,
    netCA,
    netAC,
    netSendAB,
    netSendBC,
    netInjectB,
    netInjectC,
    netPolarity,
    netFbDelay,
    netFbFilter,
    netFbDrive,
    netDamping,
    netWidth,
    netInject,
    netTap,
    netMix,
    netRepipe,
    loopOn,
    loopAmount,
    loopSource,
    loopDest,
    loopFilter,
    loopDelay,
    loopPolarity,
    loopSat,
    mod9Src,
    mod9Dst,
    mod9Depth,
    mod10Src,
    mod10Dst,
    mod10Depth,
    mod11Src,
    mod11Dst,
    mod11Depth,
    mod12Src,
    mod12Dst,
    mod12Depth,
    mod13Src,
    mod13Dst,
    mod13Depth,
    mod14Src,
    mod14Dst,
    mod14Depth,
    mod15Src,
    mod15Dst,
    mod15Depth,
    mod16Src,
    mod16Dst,
    mod16Depth,
    quality,
    morphOn,
    morphPosition,
    morphMode,
    randomMutation,
    randomWild,
    filter1On,
    filter1Position,
    filter1Type,
    filter1Cutoff,
    filter1Resonance,
    filter1Drive,
    filter1Keytrack,
    filter1Env,
    filter1Morph,
    filter1Slope,
    filter1Vowel,
    filter1Mix,
    filter2On,
    filter2Position,
    filter2Type,
    filter2Cutoff,
    filter2Resonance,
    filter2Drive,
    filter2Keytrack,
    filter2Env,
    filter2Morph,
    filter2Slope,
    filter2Vowel,
    filter2Mix,
    filter3On,
    filter3Position,
    filter3Type,
    filter3Cutoff,
    filter3Resonance,
    filter3Drive,
    filter3Keytrack,
    filter3Env,
    filter3Morph,
    filter3Slope,
    filter3Vowel,
    filter3Mix,
    contactOn,
    contactSource,
    contactDestination,
    contactGap,
    contactStiffness,
    contactHardness,
    contactDamping,
    contactFriction,
    contactAsymmetry,
    contactAmount,
    contactPolarity,
    contactQuality,
    stereoMode,
    stereoDivergence,
    stereoCoupling,
    stereoExciterSpread,
    stereoPickupSpread,
    stereoDamping,
    stereoRotation,
    stereoWidth,
    stereoMonoBass,
    symOn,
    symSend,
    symReturn,
    symDamper,
    symDecay,
    symDamping,
    symBrightness,
    symDetune,
    symSpread,
    symTuning,
    symRoot,
    symCount,
    symThreshold,
    symFreeze,
    symClear,
    symCapture,
    symInterval1,
    symInterval2,
    symInterval3,
    symInterval4,
    symInterval5,
    symInterval6,
    symInterval7,
    symInterval8,
    symInterval9,
    symInterval10,
    symInterval11,
    symInterval12,
    Count
};

inline constexpr int kNumParams = (int) P::Count;
inline constexpr int kNumParamsV01 = 120;   // parameters that existed in v0.1

namespace ids
{
inline constexpr const char* excNoise = "exc_noise";
inline constexpr const char* excNoiseColor = "exc_noise_color";
inline constexpr const char* excPressure = "exc_pressure";
inline constexpr const char* excPluck = "exc_pluck";
inline constexpr const char* excPluckLength = "exc_pluck_len";
inline constexpr const char* excLowpass = "exc_lp";
inline constexpr const char* excHighpass = "exc_hp";
inline constexpr const char* excTurbulence = "exc_turb";
inline constexpr const char* excVelocity = "exc_vel";
inline constexpr const char* excExternalIn = "exc_ext_in";
inline constexpr const char* excKeyTrack = "exc_keytrack";
inline constexpr const char* excAttackClick = "exc_attack_click";
inline constexpr const char* excReleaseNoise = "exc_release_noise";
inline constexpr const char* excBreathRandom = "exc_breath_random";
inline constexpr const char* excReed = "exc_reed";
inline constexpr const char* envAttack = "env_attack";
inline constexpr const char* envDecay = "env_decay";
inline constexpr const char* envSustain = "env_sustain";
inline constexpr const char* envRelease = "env_release";
inline constexpr const char* envVelToPressure = "env_vel_pressure";
inline constexpr const char* artPressBright = "art_press_bright";
inline constexpr const char* artFlowPitch = "art_flow_pitch";
inline constexpr const char* artInstability = "art_instability";
inline constexpr const char* artVariation = "art_variation";
inline constexpr const char* artCoupling = "art_coupling";
inline constexpr const char* resCoarse = "res_coarse";
inline constexpr const char* resFine = "res_fine";
inline constexpr const char* resLength = "res_length";
inline constexpr const char* resKeyTrack = "res_keytrack";
inline constexpr const char* resFeedback = "res_feedback";
inline constexpr const char* resDamping = "res_damping";
inline constexpr const char* resBrightness = "res_brightness";
inline constexpr const char* resDispersion = "res_dispersion";
inline constexpr const char* resShape = "res_shape";
inline constexpr const char* resReflection = "res_reflect";
inline constexpr const char* resSaturation = "res_saturation";
inline constexpr const char* resMode = "res_mode";
inline constexpr const char* resBodyFreq = "res_body_freq";
inline constexpr const char* resBodyRes = "res_body_res";
inline constexpr const char* resBodyMix = "res_body_mix";
inline constexpr const char* resBodyTrack = "res_body_track";
inline constexpr const char* lfo1Shape = "lfo1_shape";
inline constexpr const char* lfo1Rate = "lfo1_rate";
inline constexpr const char* lfo1Sync = "lfo1_sync";
inline constexpr const char* lfo1Div = "lfo1_div";
inline constexpr const char* lfo1Mode = "lfo1_mode";
inline constexpr const char* lfo1Fade = "lfo1_fade";
inline constexpr const char* lfo1Phase = "lfo1_phase";
inline constexpr const char* lfo2Shape = "lfo2_shape";
inline constexpr const char* lfo2Rate = "lfo2_rate";
inline constexpr const char* lfo2Sync = "lfo2_sync";
inline constexpr const char* lfo2Div = "lfo2_div";
inline constexpr const char* lfo2Mode = "lfo2_mode";
inline constexpr const char* lfo2Fade = "lfo2_fade";
inline constexpr const char* lfo2Phase = "lfo2_phase";
inline constexpr const char* lfo3Shape = "lfo3_shape";
inline constexpr const char* lfo3Rate = "lfo3_rate";
inline constexpr const char* lfo3Sync = "lfo3_sync";
inline constexpr const char* lfo3Div = "lfo3_div";
inline constexpr const char* lfo3Mode = "lfo3_mode";
inline constexpr const char* lfo3Fade = "lfo3_fade";
inline constexpr const char* lfo3Phase = "lfo3_phase";
inline constexpr const char* menvAttack = "menv_attack";
inline constexpr const char* menvDecay = "menv_decay";
inline constexpr const char* menvSustain = "menv_sustain";
inline constexpr const char* menvRelease = "menv_release";
inline constexpr const char* mod1Src = "mod1_src";
inline constexpr const char* mod1Dst = "mod1_dst";
inline constexpr const char* mod1Depth = "mod1_depth";
inline constexpr const char* mod2Src = "mod2_src";
inline constexpr const char* mod2Dst = "mod2_dst";
inline constexpr const char* mod2Depth = "mod2_depth";
inline constexpr const char* mod3Src = "mod3_src";
inline constexpr const char* mod3Dst = "mod3_dst";
inline constexpr const char* mod3Depth = "mod3_depth";
inline constexpr const char* mod4Src = "mod4_src";
inline constexpr const char* mod4Dst = "mod4_dst";
inline constexpr const char* mod4Depth = "mod4_depth";
inline constexpr const char* mod5Src = "mod5_src";
inline constexpr const char* mod5Dst = "mod5_dst";
inline constexpr const char* mod5Depth = "mod5_depth";
inline constexpr const char* mod6Src = "mod6_src";
inline constexpr const char* mod6Dst = "mod6_dst";
inline constexpr const char* mod6Depth = "mod6_depth";
inline constexpr const char* mod7Src = "mod7_src";
inline constexpr const char* mod7Dst = "mod7_dst";
inline constexpr const char* mod7Depth = "mod7_depth";
inline constexpr const char* mod8Src = "mod8_src";
inline constexpr const char* mod8Dst = "mod8_dst";
inline constexpr const char* mod8Depth = "mod8_depth";
inline constexpr const char* chorusMix = "chorus_mix";
inline constexpr const char* chorusRate = "chorus_rate";
inline constexpr const char* chorusDepth = "chorus_depth";
inline constexpr const char* chorusWidth = "chorus_width";
inline constexpr const char* delayMix = "delay_mix";
inline constexpr const char* delayTime = "delay_time";
inline constexpr const char* delaySync = "delay_sync";
inline constexpr const char* delayDiv = "delay_div";
inline constexpr const char* delayFeedback = "delay_feedback";
inline constexpr const char* delayTone = "delay_tone";
inline constexpr const char* delayPingPong = "delay_pingpong";
inline constexpr const char* reverbMix = "rev_mix";
inline constexpr const char* reverbSize = "rev_size";
inline constexpr const char* reverbDecay = "rev_decay";
inline constexpr const char* reverbDamping = "rev_damp";
inline constexpr const char* reverbPreDelay = "rev_predelay";
inline constexpr const char* reverbWidth = "rev_width";
inline constexpr const char* reverbModulation = "rev_mod";
inline constexpr const char* voiceMode = "voice_mode";
inline constexpr const char* voiceCount = "voice_count";
inline constexpr const char* glideTime = "glide_time";
inline constexpr const char* glideLegatoOnly = "glide_legato";
inline constexpr const char* unisonVoices = "unison_voices";
inline constexpr const char* unisonDetune = "unison_detune";
inline constexpr const char* unisonSpread = "unison_spread";
inline constexpr const char* bendRange = "bend_range";
inline constexpr const char* mpeEnabled = "mpe_enable";
inline constexpr const char* outGain = "out_gain";
inline constexpr const char* outHighpass = "out_hp";
inline constexpr const char* limiterOn = "limiter_on";
inline constexpr const char* exaModel = "exa_model";
inline constexpr const char* exaLevel = "exa_level";
inline constexpr const char* exaCoarse = "exa_coarse";
inline constexpr const char* exaFine = "exa_fine";
inline constexpr const char* exaKeytrack = "exa_keytrack";
inline constexpr const char* exaRetrig = "exa_retrig";
inline constexpr const char* exaVariation = "exa_variation";
inline constexpr const char* exaVel = "exa_vel";
inline constexpr const char* exaPress = "exa_press";
inline constexpr const char* exaDrift = "exa_drift";
inline constexpr const char* exaPhase = "exa_phase";
inline constexpr const char* exaTone = "exa_tone";
inline constexpr const char* exaWaveShape = "exa_wave_shape";
inline constexpr const char* exaWavePw = "exa_wave_pw";
inline constexpr const char* exaWaveSub = "exa_wave_sub";
inline constexpr const char* exaWavePd = "exa_wave_pd";
inline constexpr const char* exaCxComplexity = "exa_cx_complexity";
inline constexpr const char* exaCxSymmetry = "exa_cx_symmetry";
inline constexpr const char* exaCxBend = "exa_cx_bend";
inline constexpr const char* exaCxInstab = "exa_cx_instab";
inline constexpr const char* exaCxSpread = "exa_cx_spread";
inline constexpr const char* exaCxWarp = "exa_cx_warp";
inline constexpr const char* exaCxFeedback = "exa_cx_feedback";
inline constexpr const char* exaCxChaos = "exa_cx_chaos";
inline constexpr const char* exaCxRatio = "exa_cx_ratio";
inline constexpr const char* exaNzColor = "exa_nz_color";
inline constexpr const char* exaNzDensity = "exa_nz_density";
inline constexpr const char* exaNzGrain = "exa_nz_grain";
inline constexpr const char* exaNzBandwidth = "exa_nz_bandwidth";
inline constexpr const char* exaNzCenter = "exa_nz_center";
inline constexpr const char* exaNzCorrelation = "exa_nz_correlation";
inline constexpr const char* exaNzSeed = "exa_nz_seed";
inline constexpr const char* exaNzWidth = "exa_nz_width";
inline constexpr const char* exaNzBurst = "exa_nz_burst";
inline constexpr const char* exaNzBurstEnv = "exa_nz_burstenv";
inline constexpr const char* exaNzTurb = "exa_nz_turb";
inline constexpr const char* exaNzGust = "exa_nz_gust";
inline constexpr const char* exaPhStiffness = "exa_ph_stiffness";
inline constexpr const char* exaPhOpening = "exa_ph_opening";
inline constexpr const char* exaPhPosition = "exa_ph_position";
inline constexpr const char* exaPhSpeed = "exa_ph_speed";
inline constexpr const char* exaPhTurb = "exa_ph_turb";
inline constexpr const char* exaPhHardness = "exa_ph_hardness";
inline constexpr const char* exaPhBright = "exa_ph_bright";
inline constexpr const char* exaScLp = "exa_sc_lp";
inline constexpr const char* exaScHp = "exa_sc_hp";
inline constexpr const char* exaScFollow = "exa_sc_follow";
inline constexpr const char* exaScTransient = "exa_sc_transient";
inline constexpr const char* exaScFreeze = "exa_sc_freeze";
inline constexpr const char* exbModel = "exb_model";
inline constexpr const char* exbLevel = "exb_level";
inline constexpr const char* exbCoarse = "exb_coarse";
inline constexpr const char* exbFine = "exb_fine";
inline constexpr const char* exbKeytrack = "exb_keytrack";
inline constexpr const char* exbRetrig = "exb_retrig";
inline constexpr const char* exbVariation = "exb_variation";
inline constexpr const char* exbVel = "exb_vel";
inline constexpr const char* exbPress = "exb_press";
inline constexpr const char* exbDrift = "exb_drift";
inline constexpr const char* exbPhase = "exb_phase";
inline constexpr const char* exbTone = "exb_tone";
inline constexpr const char* exbWaveShape = "exb_wave_shape";
inline constexpr const char* exbWavePw = "exb_wave_pw";
inline constexpr const char* exbWaveSub = "exb_wave_sub";
inline constexpr const char* exbWavePd = "exb_wave_pd";
inline constexpr const char* exbCxComplexity = "exb_cx_complexity";
inline constexpr const char* exbCxSymmetry = "exb_cx_symmetry";
inline constexpr const char* exbCxBend = "exb_cx_bend";
inline constexpr const char* exbCxInstab = "exb_cx_instab";
inline constexpr const char* exbCxSpread = "exb_cx_spread";
inline constexpr const char* exbCxWarp = "exb_cx_warp";
inline constexpr const char* exbCxFeedback = "exb_cx_feedback";
inline constexpr const char* exbCxChaos = "exb_cx_chaos";
inline constexpr const char* exbCxRatio = "exb_cx_ratio";
inline constexpr const char* exbNzColor = "exb_nz_color";
inline constexpr const char* exbNzDensity = "exb_nz_density";
inline constexpr const char* exbNzGrain = "exb_nz_grain";
inline constexpr const char* exbNzBandwidth = "exb_nz_bandwidth";
inline constexpr const char* exbNzCenter = "exb_nz_center";
inline constexpr const char* exbNzCorrelation = "exb_nz_correlation";
inline constexpr const char* exbNzSeed = "exb_nz_seed";
inline constexpr const char* exbNzWidth = "exb_nz_width";
inline constexpr const char* exbNzBurst = "exb_nz_burst";
inline constexpr const char* exbNzBurstEnv = "exb_nz_burstenv";
inline constexpr const char* exbNzTurb = "exb_nz_turb";
inline constexpr const char* exbNzGust = "exb_nz_gust";
inline constexpr const char* exbPhStiffness = "exb_ph_stiffness";
inline constexpr const char* exbPhOpening = "exb_ph_opening";
inline constexpr const char* exbPhPosition = "exb_ph_position";
inline constexpr const char* exbPhSpeed = "exb_ph_speed";
inline constexpr const char* exbPhTurb = "exb_ph_turb";
inline constexpr const char* exbPhHardness = "exb_ph_hardness";
inline constexpr const char* exbPhBright = "exb_ph_bright";
inline constexpr const char* exbScLp = "exb_sc_lp";
inline constexpr const char* exbScHp = "exb_sc_hp";
inline constexpr const char* exbScFollow = "exb_sc_follow";
inline constexpr const char* exbScTransient = "exb_sc_transient";
inline constexpr const char* exbScFreeze = "exb_sc_freeze";
inline constexpr const char* exbSync = "exb_sync";
inline constexpr const char* mixMode = "mix_mode";
inline constexpr const char* mixInteraction = "mix_interaction";
inline constexpr const char* mixBalance = "mix_balance";
inline constexpr const char* mixDepth = "mix_depth";
inline constexpr const char* mixB2A = "mix_b2a";
inline constexpr const char* mixA2B = "mix_a2b";
inline constexpr const char* mixDcBlock = "mix_dcblock";
inline constexpr const char* mixNormalize = "mix_normalize";
inline constexpr const char* mixDrive = "mix_drive";
inline constexpr const char* preType = "pre_type";
inline constexpr const char* preRes = "pre_res";
inline constexpr const char* preDrive = "pre_drive";
inline constexpr const char* preBias = "pre_bias";
inline constexpr const char* preSlew = "pre_slew";
inline constexpr const char* preTransient = "pre_transient";
inline constexpr const char* preEnv = "pre_env";
inline constexpr const char* preOrder = "pre_order";
inline constexpr const char* wfOn = "wf_on";
inline constexpr const char* wfFold = "wf_fold";
inline constexpr const char* wfDrive = "wf_drive";
inline constexpr const char* wfSymmetry = "wf_symmetry";
inline constexpr const char* wfBias = "wf_bias";
inline constexpr const char* wfStages = "wf_stages";
inline constexpr const char* wfMode = "wf_mode";
inline constexpr const char* wfShape = "wf_shape";
inline constexpr const char* wfMix = "wf_mix";
inline constexpr const char* wfComp = "wf_comp";
inline constexpr const char* wfLp = "wf_lp";
inline constexpr const char* dynAmount = "dyn_amount";
inline constexpr const char* resOn = "res_on";
inline constexpr const char* resInput = "res_input";
inline constexpr const char* resOutput = "res_output";
inline constexpr const char* resPan = "res_pan";
inline constexpr const char* resWidth = "res_width";
inline constexpr const char* resPickup = "res_pickup";
inline constexpr const char* resInharm = "res_inharm";
inline constexpr const char* resSize = "res_size";
inline constexpr const char* rbOn = "rb_on";
inline constexpr const char* rbType = "rb_type";
inline constexpr const char* rbInput = "rb_input";
inline constexpr const char* rbOutput = "rb_output";
inline constexpr const char* rbCoarse = "rb_coarse";
inline constexpr const char* rbFine = "rb_fine";
inline constexpr const char* rbRatio = "rb_ratio";
inline constexpr const char* rbKeytrack = "rb_keytrack";
inline constexpr const char* rbFeedback = "rb_feedback";
inline constexpr const char* rbDamping = "rb_damping";
inline constexpr const char* rbBrightness = "rb_brightness";
inline constexpr const char* rbDispersion = "rb_dispersion";
inline constexpr const char* rbInharm = "rb_inharm";
inline constexpr const char* rbShape = "rb_shape";
inline constexpr const char* rbReflect = "rb_reflect";
inline constexpr const char* rbSaturation = "rb_saturation";
inline constexpr const char* rbReed = "rb_reed";
inline constexpr const char* rbSize = "rb_size";
inline constexpr const char* rbPickup = "rb_pickup";
inline constexpr const char* rbPan = "rb_pan";
inline constexpr const char* rbWidth = "rb_width";
inline constexpr const char* rcOn = "rc_on";
inline constexpr const char* rcType = "rc_type";
inline constexpr const char* rcInput = "rc_input";
inline constexpr const char* rcOutput = "rc_output";
inline constexpr const char* rcCoarse = "rc_coarse";
inline constexpr const char* rcFine = "rc_fine";
inline constexpr const char* rcRatio = "rc_ratio";
inline constexpr const char* rcKeytrack = "rc_keytrack";
inline constexpr const char* rcFeedback = "rc_feedback";
inline constexpr const char* rcDamping = "rc_damping";
inline constexpr const char* rcBrightness = "rc_brightness";
inline constexpr const char* rcDispersion = "rc_dispersion";
inline constexpr const char* rcInharm = "rc_inharm";
inline constexpr const char* rcShape = "rc_shape";
inline constexpr const char* rcReflect = "rc_reflect";
inline constexpr const char* rcSaturation = "rc_saturation";
inline constexpr const char* rcReed = "rc_reed";
inline constexpr const char* rcSize = "rc_size";
inline constexpr const char* rcPickup = "rc_pickup";
inline constexpr const char* rcPan = "rc_pan";
inline constexpr const char* rcWidth = "rc_width";
inline constexpr const char* netMode = "net_mode";
inline constexpr const char* netFeedback = "net_feedback";
inline constexpr const char* netAB = "net_ab";
inline constexpr const char* netBA = "net_ba";
inline constexpr const char* netBC = "net_bc";
inline constexpr const char* netCB = "net_cb";
inline constexpr const char* netCA = "net_ca";
inline constexpr const char* netAC = "net_ac";
inline constexpr const char* netSendAB = "net_send_ab";
inline constexpr const char* netSendBC = "net_send_bc";
inline constexpr const char* netInjectB = "net_inject_b";
inline constexpr const char* netInjectC = "net_inject_c";
inline constexpr const char* netPolarity = "net_polarity";
inline constexpr const char* netFbDelay = "net_fb_delay";
inline constexpr const char* netFbFilter = "net_fb_filter";
inline constexpr const char* netFbDrive = "net_fb_drive";
inline constexpr const char* netDamping = "net_damping";
inline constexpr const char* netWidth = "net_width";
inline constexpr const char* netInject = "net_inject";
inline constexpr const char* netTap = "net_tap";
inline constexpr const char* netMix = "net_mix";
inline constexpr const char* netRepipe = "net_repipe";
inline constexpr const char* loopOn = "loop_on";
inline constexpr const char* loopAmount = "loop_amount";
inline constexpr const char* loopSource = "loop_source";
inline constexpr const char* loopDest = "loop_dest";
inline constexpr const char* loopFilter = "loop_filter";
inline constexpr const char* loopDelay = "loop_delay";
inline constexpr const char* loopPolarity = "loop_polarity";
inline constexpr const char* loopSat = "loop_sat";
inline constexpr const char* mod9Src = "mod9_src";
inline constexpr const char* mod9Dst = "mod9_dst";
inline constexpr const char* mod9Depth = "mod9_depth";
inline constexpr const char* mod10Src = "mod10_src";
inline constexpr const char* mod10Dst = "mod10_dst";
inline constexpr const char* mod10Depth = "mod10_depth";
inline constexpr const char* mod11Src = "mod11_src";
inline constexpr const char* mod11Dst = "mod11_dst";
inline constexpr const char* mod11Depth = "mod11_depth";
inline constexpr const char* mod12Src = "mod12_src";
inline constexpr const char* mod12Dst = "mod12_dst";
inline constexpr const char* mod12Depth = "mod12_depth";
inline constexpr const char* mod13Src = "mod13_src";
inline constexpr const char* mod13Dst = "mod13_dst";
inline constexpr const char* mod13Depth = "mod13_depth";
inline constexpr const char* mod14Src = "mod14_src";
inline constexpr const char* mod14Dst = "mod14_dst";
inline constexpr const char* mod14Depth = "mod14_depth";
inline constexpr const char* mod15Src = "mod15_src";
inline constexpr const char* mod15Dst = "mod15_dst";
inline constexpr const char* mod15Depth = "mod15_depth";
inline constexpr const char* mod16Src = "mod16_src";
inline constexpr const char* mod16Dst = "mod16_dst";
inline constexpr const char* mod16Depth = "mod16_depth";
inline constexpr const char* quality = "quality";
inline constexpr const char* morphOn = "morph_on";
inline constexpr const char* morphPosition = "morph_position";
inline constexpr const char* morphMode = "morph_mode";
inline constexpr const char* randomMutation = "random_mutation";
inline constexpr const char* randomWild = "random_wild";
inline constexpr const char* filter1On = "filter1_on";
inline constexpr const char* filter1Position = "filter1_position";
inline constexpr const char* filter1Type = "filter1_type";
inline constexpr const char* filter1Cutoff = "filter1_cutoff";
inline constexpr const char* filter1Resonance = "filter1_resonance";
inline constexpr const char* filter1Drive = "filter1_drive";
inline constexpr const char* filter1Keytrack = "filter1_keytrack";
inline constexpr const char* filter1Env = "filter1_env";
inline constexpr const char* filter1Morph = "filter1_morph";
inline constexpr const char* filter1Slope = "filter1_slope";
inline constexpr const char* filter1Vowel = "filter1_vowel";
inline constexpr const char* filter1Mix = "filter1_mix";
inline constexpr const char* filter2On = "filter2_on";
inline constexpr const char* filter2Position = "filter2_position";
inline constexpr const char* filter2Type = "filter2_type";
inline constexpr const char* filter2Cutoff = "filter2_cutoff";
inline constexpr const char* filter2Resonance = "filter2_resonance";
inline constexpr const char* filter2Drive = "filter2_drive";
inline constexpr const char* filter2Keytrack = "filter2_keytrack";
inline constexpr const char* filter2Env = "filter2_env";
inline constexpr const char* filter2Morph = "filter2_morph";
inline constexpr const char* filter2Slope = "filter2_slope";
inline constexpr const char* filter2Vowel = "filter2_vowel";
inline constexpr const char* filter2Mix = "filter2_mix";
inline constexpr const char* filter3On = "filter3_on";
inline constexpr const char* filter3Position = "filter3_position";
inline constexpr const char* filter3Type = "filter3_type";
inline constexpr const char* filter3Cutoff = "filter3_cutoff";
inline constexpr const char* filter3Resonance = "filter3_resonance";
inline constexpr const char* filter3Drive = "filter3_drive";
inline constexpr const char* filter3Keytrack = "filter3_keytrack";
inline constexpr const char* filter3Env = "filter3_env";
inline constexpr const char* filter3Morph = "filter3_morph";
inline constexpr const char* filter3Slope = "filter3_slope";
inline constexpr const char* filter3Vowel = "filter3_vowel";
inline constexpr const char* filter3Mix = "filter3_mix";
inline constexpr const char* contactOn = "contact_on";
inline constexpr const char* contactSource = "contact_source";
inline constexpr const char* contactDestination = "contact_destination";
inline constexpr const char* contactGap = "contact_gap";
inline constexpr const char* contactStiffness = "contact_stiffness";
inline constexpr const char* contactHardness = "contact_hardness";
inline constexpr const char* contactDamping = "contact_damping";
inline constexpr const char* contactFriction = "contact_friction";
inline constexpr const char* contactAsymmetry = "contact_asymmetry";
inline constexpr const char* contactAmount = "contact_amount";
inline constexpr const char* contactPolarity = "contact_polarity";
inline constexpr const char* contactQuality = "contact_quality";
inline constexpr const char* stereoMode = "stereo_mode";
inline constexpr const char* stereoDivergence = "stereo_divergence";
inline constexpr const char* stereoCoupling = "stereo_coupling";
inline constexpr const char* stereoExciterSpread = "stereo_exciter_spread";
inline constexpr const char* stereoPickupSpread = "stereo_pickup_spread";
inline constexpr const char* stereoDamping = "stereo_damping";
inline constexpr const char* stereoRotation = "stereo_rotation";
inline constexpr const char* stereoWidth = "stereo_width";
inline constexpr const char* stereoMonoBass = "stereo_mono_bass";
inline constexpr const char* symOn = "sym_on";
inline constexpr const char* symSend = "sym_send";
inline constexpr const char* symReturn = "sym_return";
inline constexpr const char* symDamper = "sym_damper";
inline constexpr const char* symDecay = "sym_decay";
inline constexpr const char* symDamping = "sym_damping";
inline constexpr const char* symBrightness = "sym_brightness";
inline constexpr const char* symDetune = "sym_detune";
inline constexpr const char* symSpread = "sym_spread";
inline constexpr const char* symTuning = "sym_tuning";
inline constexpr const char* symRoot = "sym_root";
inline constexpr const char* symCount = "sym_count";
inline constexpr const char* symThreshold = "sym_threshold";
inline constexpr const char* symFreeze = "sym_freeze";
inline constexpr const char* symClear = "sym_clear";
inline constexpr const char* symCapture = "sym_capture";
inline constexpr const char* symInterval1 = "sym_interval1";
inline constexpr const char* symInterval2 = "sym_interval2";
inline constexpr const char* symInterval3 = "sym_interval3";
inline constexpr const char* symInterval4 = "sym_interval4";
inline constexpr const char* symInterval5 = "sym_interval5";
inline constexpr const char* symInterval6 = "sym_interval6";
inline constexpr const char* symInterval7 = "sym_interval7";
inline constexpr const char* symInterval8 = "sym_interval8";
inline constexpr const char* symInterval9 = "sym_interval9";
inline constexpr const char* symInterval10 = "sym_interval10";
inline constexpr const char* symInterval11 = "sym_interval11";
inline constexpr const char* symInterval12 = "sym_interval12";

inline constexpr const char* const all[kNumParams] = {
    "exc_noise",
    "exc_noise_color",
    "exc_pressure",
    "exc_pluck",
    "exc_pluck_len",
    "exc_lp",
    "exc_hp",
    "exc_turb",
    "exc_vel",
    "exc_ext_in",
    "exc_keytrack",
    "exc_attack_click",
    "exc_release_noise",
    "exc_breath_random",
    "exc_reed",
    "env_attack",
    "env_decay",
    "env_sustain",
    "env_release",
    "env_vel_pressure",
    "art_press_bright",
    "art_flow_pitch",
    "art_instability",
    "art_variation",
    "art_coupling",
    "res_coarse",
    "res_fine",
    "res_length",
    "res_keytrack",
    "res_feedback",
    "res_damping",
    "res_brightness",
    "res_dispersion",
    "res_shape",
    "res_reflect",
    "res_saturation",
    "res_mode",
    "res_body_freq",
    "res_body_res",
    "res_body_mix",
    "res_body_track",
    "lfo1_shape",
    "lfo1_rate",
    "lfo1_sync",
    "lfo1_div",
    "lfo1_mode",
    "lfo1_fade",
    "lfo1_phase",
    "lfo2_shape",
    "lfo2_rate",
    "lfo2_sync",
    "lfo2_div",
    "lfo2_mode",
    "lfo2_fade",
    "lfo2_phase",
    "lfo3_shape",
    "lfo3_rate",
    "lfo3_sync",
    "lfo3_div",
    "lfo3_mode",
    "lfo3_fade",
    "lfo3_phase",
    "menv_attack",
    "menv_decay",
    "menv_sustain",
    "menv_release",
    "mod1_src",
    "mod1_dst",
    "mod1_depth",
    "mod2_src",
    "mod2_dst",
    "mod2_depth",
    "mod3_src",
    "mod3_dst",
    "mod3_depth",
    "mod4_src",
    "mod4_dst",
    "mod4_depth",
    "mod5_src",
    "mod5_dst",
    "mod5_depth",
    "mod6_src",
    "mod6_dst",
    "mod6_depth",
    "mod7_src",
    "mod7_dst",
    "mod7_depth",
    "mod8_src",
    "mod8_dst",
    "mod8_depth",
    "chorus_mix",
    "chorus_rate",
    "chorus_depth",
    "chorus_width",
    "delay_mix",
    "delay_time",
    "delay_sync",
    "delay_div",
    "delay_feedback",
    "delay_tone",
    "delay_pingpong",
    "rev_mix",
    "rev_size",
    "rev_decay",
    "rev_damp",
    "rev_predelay",
    "rev_width",
    "rev_mod",
    "voice_mode",
    "voice_count",
    "glide_time",
    "glide_legato",
    "unison_voices",
    "unison_detune",
    "unison_spread",
    "bend_range",
    "mpe_enable",
    "out_gain",
    "out_hp",
    "limiter_on",
    "exa_model",
    "exa_level",
    "exa_coarse",
    "exa_fine",
    "exa_keytrack",
    "exa_retrig",
    "exa_variation",
    "exa_vel",
    "exa_press",
    "exa_drift",
    "exa_phase",
    "exa_tone",
    "exa_wave_shape",
    "exa_wave_pw",
    "exa_wave_sub",
    "exa_wave_pd",
    "exa_cx_complexity",
    "exa_cx_symmetry",
    "exa_cx_bend",
    "exa_cx_instab",
    "exa_cx_spread",
    "exa_cx_warp",
    "exa_cx_feedback",
    "exa_cx_chaos",
    "exa_cx_ratio",
    "exa_nz_color",
    "exa_nz_density",
    "exa_nz_grain",
    "exa_nz_bandwidth",
    "exa_nz_center",
    "exa_nz_correlation",
    "exa_nz_seed",
    "exa_nz_width",
    "exa_nz_burst",
    "exa_nz_burstenv",
    "exa_nz_turb",
    "exa_nz_gust",
    "exa_ph_stiffness",
    "exa_ph_opening",
    "exa_ph_position",
    "exa_ph_speed",
    "exa_ph_turb",
    "exa_ph_hardness",
    "exa_ph_bright",
    "exa_sc_lp",
    "exa_sc_hp",
    "exa_sc_follow",
    "exa_sc_transient",
    "exa_sc_freeze",
    "exb_model",
    "exb_level",
    "exb_coarse",
    "exb_fine",
    "exb_keytrack",
    "exb_retrig",
    "exb_variation",
    "exb_vel",
    "exb_press",
    "exb_drift",
    "exb_phase",
    "exb_tone",
    "exb_wave_shape",
    "exb_wave_pw",
    "exb_wave_sub",
    "exb_wave_pd",
    "exb_cx_complexity",
    "exb_cx_symmetry",
    "exb_cx_bend",
    "exb_cx_instab",
    "exb_cx_spread",
    "exb_cx_warp",
    "exb_cx_feedback",
    "exb_cx_chaos",
    "exb_cx_ratio",
    "exb_nz_color",
    "exb_nz_density",
    "exb_nz_grain",
    "exb_nz_bandwidth",
    "exb_nz_center",
    "exb_nz_correlation",
    "exb_nz_seed",
    "exb_nz_width",
    "exb_nz_burst",
    "exb_nz_burstenv",
    "exb_nz_turb",
    "exb_nz_gust",
    "exb_ph_stiffness",
    "exb_ph_opening",
    "exb_ph_position",
    "exb_ph_speed",
    "exb_ph_turb",
    "exb_ph_hardness",
    "exb_ph_bright",
    "exb_sc_lp",
    "exb_sc_hp",
    "exb_sc_follow",
    "exb_sc_transient",
    "exb_sc_freeze",
    "exb_sync",
    "mix_mode",
    "mix_interaction",
    "mix_balance",
    "mix_depth",
    "mix_b2a",
    "mix_a2b",
    "mix_dcblock",
    "mix_normalize",
    "mix_drive",
    "pre_type",
    "pre_res",
    "pre_drive",
    "pre_bias",
    "pre_slew",
    "pre_transient",
    "pre_env",
    "pre_order",
    "wf_on",
    "wf_fold",
    "wf_drive",
    "wf_symmetry",
    "wf_bias",
    "wf_stages",
    "wf_mode",
    "wf_shape",
    "wf_mix",
    "wf_comp",
    "wf_lp",
    "dyn_amount",
    "res_on",
    "res_input",
    "res_output",
    "res_pan",
    "res_width",
    "res_pickup",
    "res_inharm",
    "res_size",
    "rb_on",
    "rb_type",
    "rb_input",
    "rb_output",
    "rb_coarse",
    "rb_fine",
    "rb_ratio",
    "rb_keytrack",
    "rb_feedback",
    "rb_damping",
    "rb_brightness",
    "rb_dispersion",
    "rb_inharm",
    "rb_shape",
    "rb_reflect",
    "rb_saturation",
    "rb_reed",
    "rb_size",
    "rb_pickup",
    "rb_pan",
    "rb_width",
    "rc_on",
    "rc_type",
    "rc_input",
    "rc_output",
    "rc_coarse",
    "rc_fine",
    "rc_ratio",
    "rc_keytrack",
    "rc_feedback",
    "rc_damping",
    "rc_brightness",
    "rc_dispersion",
    "rc_inharm",
    "rc_shape",
    "rc_reflect",
    "rc_saturation",
    "rc_reed",
    "rc_size",
    "rc_pickup",
    "rc_pan",
    "rc_width",
    "net_mode",
    "net_feedback",
    "net_ab",
    "net_ba",
    "net_bc",
    "net_cb",
    "net_ca",
    "net_ac",
    "net_send_ab",
    "net_send_bc",
    "net_inject_b",
    "net_inject_c",
    "net_polarity",
    "net_fb_delay",
    "net_fb_filter",
    "net_fb_drive",
    "net_damping",
    "net_width",
    "net_inject",
    "net_tap",
    "net_mix",
    "net_repipe",
    "loop_on",
    "loop_amount",
    "loop_source",
    "loop_dest",
    "loop_filter",
    "loop_delay",
    "loop_polarity",
    "loop_sat",
    "mod9_src",
    "mod9_dst",
    "mod9_depth",
    "mod10_src",
    "mod10_dst",
    "mod10_depth",
    "mod11_src",
    "mod11_dst",
    "mod11_depth",
    "mod12_src",
    "mod12_dst",
    "mod12_depth",
    "mod13_src",
    "mod13_dst",
    "mod13_depth",
    "mod14_src",
    "mod14_dst",
    "mod14_depth",
    "mod15_src",
    "mod15_dst",
    "mod15_depth",
    "mod16_src",
    "mod16_dst",
    "mod16_depth",
    "quality",
    "morph_on",
    "morph_position",
    "morph_mode",
    "random_mutation",
    "random_wild",
    "filter1_on",
    "filter1_position",
    "filter1_type",
    "filter1_cutoff",
    "filter1_resonance",
    "filter1_drive",
    "filter1_keytrack",
    "filter1_env",
    "filter1_morph",
    "filter1_slope",
    "filter1_vowel",
    "filter1_mix",
    "filter2_on",
    "filter2_position",
    "filter2_type",
    "filter2_cutoff",
    "filter2_resonance",
    "filter2_drive",
    "filter2_keytrack",
    "filter2_env",
    "filter2_morph",
    "filter2_slope",
    "filter2_vowel",
    "filter2_mix",
    "filter3_on",
    "filter3_position",
    "filter3_type",
    "filter3_cutoff",
    "filter3_resonance",
    "filter3_drive",
    "filter3_keytrack",
    "filter3_env",
    "filter3_morph",
    "filter3_slope",
    "filter3_vowel",
    "filter3_mix",
    "contact_on",
    "contact_source",
    "contact_destination",
    "contact_gap",
    "contact_stiffness",
    "contact_hardness",
    "contact_damping",
    "contact_friction",
    "contact_asymmetry",
    "contact_amount",
    "contact_polarity",
    "contact_quality",
    "stereo_mode",
    "stereo_divergence",
    "stereo_coupling",
    "stereo_exciter_spread",
    "stereo_pickup_spread",
    "stereo_damping",
    "stereo_rotation",
    "stereo_width",
    "stereo_mono_bass",
    "sym_on",
    "sym_send",
    "sym_return",
    "sym_damper",
    "sym_decay",
    "sym_damping",
    "sym_brightness",
    "sym_detune",
    "sym_spread",
    "sym_tuning",
    "sym_root",
    "sym_count",
    "sym_threshold",
    "sym_freeze",
    "sym_clear",
    "sym_capture",
    "sym_interval1",
    "sym_interval2",
    "sym_interval3",
    "sym_interval4",
    "sym_interval5",
    "sym_interval6",
    "sym_interval7",
    "sym_interval8",
    "sym_interval9",
    "sym_interval10",
    "sym_interval11",
    "sym_interval12",
};

inline constexpr const char* id (P p) noexcept { return all[(int) p]; }

inline constexpr int numLFOs     = 3;
inline constexpr int numModSlots = 16;
inline constexpr int numModSlotsV01 = 8;

inline constexpr const char* lfoShapeSuffix = "_shape";
inline constexpr const char* lfoRateSuffix = "_rate";
inline constexpr const char* lfoSyncSuffix = "_sync";
inline constexpr const char* lfoDivSuffix = "_div";
inline constexpr const char* lfoModeSuffix = "_mode";
inline constexpr const char* lfoFadeSuffix = "_fade";
inline constexpr const char* lfoPhaseSuffix = "_phase";
inline constexpr const char* modSrcSuffix = "_src";
inline constexpr const char* modDstSuffix = "_dst";
inline constexpr const char* modDepthSuffix = "_depth";

inline juce::String lfoParam (int lfoIndex1Based, const char* suffix) { return "lfo" + juce::String (lfoIndex1Based) + suffix; }
inline juce::String modParam (int slotIndex1Based, const char* suffix) { return "mod" + juce::String (slotIndex1Based) + suffix; }

enum class LfoField { Shape, Rate, Sync, Div, Mode, Fade, Phase };
enum class ModField { Src, Dst, Depth };
/** Enum of an LFO parameter (LFO 1..3). */
inline constexpr P lfoP (int lfoIndex1Based, LfoField f) noexcept { return (P) ((int) P::lfo1Shape + (lfoIndex1Based - 1) * 7 + (int) f); }
/** Enum of a matrix slot parameter (slot 1..16). */
inline constexpr P modP (int slotIndex1Based, ModField f) noexcept
{
    return slotIndex1Based <= numModSlotsV01 ? (P) ((int) P::mod1Src + (slotIndex1Based - 1) * 3 + (int) f)
                                             : (P) ((int) P::mod9Src + (slotIndex1Based - 9) * 3 + (int) f);
}
} // namespace ids
} // namespace aeriform
