#pragma once
#include "AdvancedBindings.h"
namespace aeriform {
inline constexpr P rackTypes[]{P::rack1Type,P::rack2Type,P::rack3Type,P::rack4Type};
inline constexpr P rackEnables[]{P::rack1Enabled,P::rack2Enabled,P::rack3Enabled,P::rack4Enabled};
inline constexpr P rackFields[4][46] = {
 {P::rack1RdTime,P::rack1RdSync,P::rack1RdDiv,P::rack1RdFeedback,P::rack1RdType,P::rack1RdTuning,P::rack1RdTrack,P::rack1RdDamping,P::rack1RdDispersion,P::rack1RdAmount,P::rack1RdSaturation,P::rack1RdOffset,P::rack1RdMix,P::rack1ShInterval,P::rack1ShFeedback,P::rack1ShDiffusion,P::rack1ShDamping,P::rack1ShSize,P::rack1ShSpread,P::rack1ShLowCut,P::rack1ShHighCut,P::rack1ShMix,P::rack1SfFreeze,P::rack1SfCapture,P::rack1SfRelease,P::rack1SfBlur,P::rack1SfShift,P::rack1SfRandom,P::rack1SfDecay,P::rack1SfMix,P::rack1SatLow,P::rack1SatHigh,P::rack1SatMix,P::rack1SatQuality,P::rack1SatLowDrive,P::rack1SatLowModel,P::rack1SatLowMix,P::rack1SatLowOutput,P::rack1SatMidDrive,P::rack1SatMidModel,P::rack1SatMidMix,P::rack1SatMidOutput,P::rack1SatHighDrive,P::rack1SatHighModel,P::rack1SatHighMix,P::rack1SatHighOutput},
 {P::rack2RdTime,P::rack2RdSync,P::rack2RdDiv,P::rack2RdFeedback,P::rack2RdType,P::rack2RdTuning,P::rack2RdTrack,P::rack2RdDamping,P::rack2RdDispersion,P::rack2RdAmount,P::rack2RdSaturation,P::rack2RdOffset,P::rack2RdMix,P::rack2ShInterval,P::rack2ShFeedback,P::rack2ShDiffusion,P::rack2ShDamping,P::rack2ShSize,P::rack2ShSpread,P::rack2ShLowCut,P::rack2ShHighCut,P::rack2ShMix,P::rack2SfFreeze,P::rack2SfCapture,P::rack2SfRelease,P::rack2SfBlur,P::rack2SfShift,P::rack2SfRandom,P::rack2SfDecay,P::rack2SfMix,P::rack2SatLow,P::rack2SatHigh,P::rack2SatMix,P::rack2SatQuality,P::rack2SatLowDrive,P::rack2SatLowModel,P::rack2SatLowMix,P::rack2SatLowOutput,P::rack2SatMidDrive,P::rack2SatMidModel,P::rack2SatMidMix,P::rack2SatMidOutput,P::rack2SatHighDrive,P::rack2SatHighModel,P::rack2SatHighMix,P::rack2SatHighOutput},
 {P::rack3RdTime,P::rack3RdSync,P::rack3RdDiv,P::rack3RdFeedback,P::rack3RdType,P::rack3RdTuning,P::rack3RdTrack,P::rack3RdDamping,P::rack3RdDispersion,P::rack3RdAmount,P::rack3RdSaturation,P::rack3RdOffset,P::rack3RdMix,P::rack3ShInterval,P::rack3ShFeedback,P::rack3ShDiffusion,P::rack3ShDamping,P::rack3ShSize,P::rack3ShSpread,P::rack3ShLowCut,P::rack3ShHighCut,P::rack3ShMix,P::rack3SfFreeze,P::rack3SfCapture,P::rack3SfRelease,P::rack3SfBlur,P::rack3SfShift,P::rack3SfRandom,P::rack3SfDecay,P::rack3SfMix,P::rack3SatLow,P::rack3SatHigh,P::rack3SatMix,P::rack3SatQuality,P::rack3SatLowDrive,P::rack3SatLowModel,P::rack3SatLowMix,P::rack3SatLowOutput,P::rack3SatMidDrive,P::rack3SatMidModel,P::rack3SatMidMix,P::rack3SatMidOutput,P::rack3SatHighDrive,P::rack3SatHighModel,P::rack3SatHighMix,P::rack3SatHighOutput},
 {P::rack4RdTime,P::rack4RdSync,P::rack4RdDiv,P::rack4RdFeedback,P::rack4RdType,P::rack4RdTuning,P::rack4RdTrack,P::rack4RdDamping,P::rack4RdDispersion,P::rack4RdAmount,P::rack4RdSaturation,P::rack4RdOffset,P::rack4RdMix,P::rack4ShInterval,P::rack4ShFeedback,P::rack4ShDiffusion,P::rack4ShDamping,P::rack4ShSize,P::rack4ShSpread,P::rack4ShLowCut,P::rack4ShHighCut,P::rack4ShMix,P::rack4SfFreeze,P::rack4SfCapture,P::rack4SfRelease,P::rack4SfBlur,P::rack4SfShift,P::rack4SfRandom,P::rack4SfDecay,P::rack4SfMix,P::rack4SatLow,P::rack4SatHigh,P::rack4SatMix,P::rack4SatQuality,P::rack4SatLowDrive,P::rack4SatLowModel,P::rack4SatLowMix,P::rack4SatLowOutput,P::rack4SatMidDrive,P::rack4SatMidModel,P::rack4SatMidMix,P::rack4SatMidOutput,P::rack4SatHighDrive,P::rack4SatHighModel,P::rack4SatHighMix,P::rack4SatHighOutput},
};
inline constexpr P originalRackFields[] = {P::rdTime,P::rdSync,P::rdDiv,P::rdFeedback,P::rdType,P::rdTuning,P::rdTrack,P::rdDamping,P::rdDispersion,P::rdAmount,P::rdSaturation,P::rdOffset,P::rdMix,P::shInterval,P::shFeedback,P::shDiffusion,P::shDamping,P::shSize,P::shSpread,P::shLowCut,P::shHighCut,P::shMix,P::sfFreeze,P::sfCapture,P::sfRelease,P::sfBlur,P::sfShift,P::sfRandom,P::sfDecay,P::sfMix,P::satLow,P::satHigh,P::satMix,P::satQuality,P::satLowDrive,P::satLowModel,P::satLowMix,P::satLowOutput,P::satMidDrive,P::satMidModel,P::satMidMix,P::satMidOutput,P::satHighDrive,P::satHighModel,P::satHighMix,P::satHighOutput};
inline std::array<int,4> rackPermutation(int code) {std::array<int,4> order{0,1,2,3};for(int i=0;i<std::clamp(code,0,23);++i)std::next_permutation(order.begin(),order.end());return order;}
inline int rackOrderCode(std::array<int,4> order) {std::array<int,4> test{0,1,2,3};int code=0;do{if(test==order)return code;++code;}while(std::next_permutation(test.begin(),test.end()));return 0;}
}
